// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiwqv81LjAsRyM48ZDalASER3s2T0XQzA',
    appId: '1:473452498226:web:34723a61e8a4dc85199b2b',
    messagingSenderId: '473452498226',
    projectId: 'wasteapp-93fd6',
    authDomain: 'wasteapp-93fd6.firebaseapp.com',
    databaseURL: 'https://wasteapp-93fd6-default-rtdb.firebaseio.com',
    storageBucket: 'wasteapp-93fd6.firebasestorage.app',
    measurementId: 'G-DSM9FFR8EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARw-cdGfW9kIxyD6GPf7nAOBcGOW1Xum0',
    appId: '1:473452498226:android:746f3c0d6e4d763c199b2b',
    messagingSenderId: '473452498226',
    projectId: 'wasteapp-93fd6',
    databaseURL: 'https://wasteapp-93fd6-default-rtdb.firebaseio.com',
    storageBucket: 'wasteapp-93fd6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSk6fqJUl6ymLeRuClXiM1qGh2HjGSLN4',
    appId: '1:473452498226:ios:744012ac20a2d595199b2b',
    messagingSenderId: '473452498226',
    projectId: 'wasteapp-93fd6',
    databaseURL: 'https://wasteapp-93fd6-default-rtdb.firebaseio.com',
    storageBucket: 'wasteapp-93fd6.firebasestorage.app',
    iosBundleId: 'com.example.wasteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiwqv81LjAsRyM48ZDalASER3s2T0XQzA',
    appId: '1:473452498226:web:e99a1f82b86239fc199b2b',
    messagingSenderId: '473452498226',
    projectId: 'wasteapp-93fd6',
    authDomain: 'wasteapp-93fd6.firebaseapp.com',
    databaseURL: 'https://wasteapp-93fd6-default-rtdb.firebaseio.com',
    storageBucket: 'wasteapp-93fd6.firebasestorage.app',
    measurementId: 'G-4VZS0D2K9S',
  );
}
